# Dependabot configuration
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scripts/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 10
